# Per-app dev shell: same toolchains + tools as the sealed build, plus a
# `via-configure [artifact]` that runs the IDENTICAL cmake invocation into
# ./target (yielding compile_commands.json) and writes a cross-aware .clangd. So
# `nix develop .#<app>` then `via-configure && ninja -C target` reproduces the
# sealed build by hand. With no argument it configures the app's default
# artifact; a multi-platform app passes the artifact name to configure another.

{ pkgs, lib, artifactInfo }:

let
  # Firmware artifacts are not host-runnable; tests are host-only by design.
  isHostArt = m: art: (m.platform.${art.platform}.kind or "host") != "firmware";

  # Every buildable artifact of an app: all bins (host + firmware) + host tests.
  artifactArgsOf = app:
    let m = app.manifest; in
    (map (art: { inherit app art; kind = "bin"; }) (m.bin or [ ]))
    ++ (map (art: { inherit app art; kind = "test"; })
      (lib.filter (isHostArt m) (m.test or [ ])));

  # The artifact `via-configure` targets when given no argument: the bin named
  # like the package, else the first bin, else the first host test. An app with
  # nothing buildable gets a clear error instead of an empty-list crash.
  defaultArtifactOf = app:
    let
      m = app.manifest;
      bins = m.bin or [ ];
      tests = lib.filter (isHostArt m) (m.test or [ ]);
    in
    if bins != [ ]
    then { inherit app; art = lib.findFirst (b: b.name == m.package.name) (lib.head bins) bins; kind = "bin"; }
    else if tests != [ ]
    then { inherit app; art = lib.head tests; kind = "test"; }
    else throw "via: app '${app.name}' has no [[bin]] or [[test]] to configure a dev shell for";

  mkDevShell = app:
    let
      infos = map artifactInfo (artifactArgsOf app);
      defaultInfo = artifactInfo (defaultArtifactOf app);
      toolInputs = lib.unique (lib.concatMap (i: i.toolInputs) infos);

      # One `case` arm per artifact: run its exact configure, then point .clangd
      # at that build's compile DB and (cross) compiler.
      configureArm = info: ''
        ${info.artName})
          ${info.configureCmd "target"}
          cat > .clangd <<EOF
        # Generated by Via — do not commit. Points clangd at the build's compile
        # database and the (cross) compiler so system includes resolve correctly.
        CompileFlags:
          CompilationDatabase: target
          Compiler: ${info.ccPath}
        EOF
          echo "via: configured ./target for '${app.name}:${info.artName}' — now: ninja -C target"
          ;;
      '';

      viaConfigure = pkgs.writeShellScriptBin "via-configure" ''
        set -euo pipefail
        if [ ! -f Via.toml ]; then
          echo "via: run this from an app directory (no Via.toml here)" >&2; exit 1
        fi
        artifact="''${1:-${defaultInfo.artName}}"
        case "$artifact" in
        ${lib.concatMapStringsSep "\n" configureArm infos}
        *)
          echo "via: unknown artifact '$artifact' (have: ${lib.concatMapStringsSep " " (i: i.artName) infos})" >&2
          exit 1
          ;;
        esac
      '';
    in
    pkgs.mkShell {
      name = "via-${app.name}";
      packages = [ pkgs.cmake pkgs.ninja pkgs.clang-tools pkgs.gdb viaConfigure ]
        ++ toolInputs;
      shellHook = ''
        echo "via dev shell: ${app.name}  (artifacts: ${lib.concatMapStringsSep " " (i: i.artName) infos})"
        echo "  via-configure [artifact]   # configure ./target (default: ${defaultInfo.artName}) + compile_commands.json + .clangd"
        echo "  ninja -C target            # build"
      '';
    };
in
{
  inherit mkDevShell;
}
