# ViaDriver — turns the manifest-described artifact into a concrete CMake target
# by convention (no source lists). Consumes the VIA_* cache vars rendered into
# via_manifest.cmake by the Nix builder.
#
# Implements both the host path and the firmware path. It names NO -mcpu, NO
# chip define, NO arch/vendor specifics of any kind: those are declared by the
# app on its platform (cflags/ldflags/defines/includes/sources) and arrive here
# generically through the manifest. There is no MCU "family" layer.

include_guard(GLOBAL)

# Generate inc/via_build.h with build metadata (package, artifact, profile,
# active features). Always on the include path, so apps get build info without a
# build.rs equivalent.
function(_via_generate_build_header out_dir)
  file(MAKE_DIRECTORY "${out_dir}")
  set(_features "")
  foreach(_f IN LISTS VIA_FEATURES)
    string(TOUPPER "${_f}" _fu)
    string(REPLACE "-" "_" _fu "${_fu}")
    string(APPEND _features "#define VIA_FEATURE_${_fu} 1\n")
  endforeach()
  file(WRITE "${out_dir}/via_build.h"
"/* Generated by Via — do not edit, do not commit. */
#ifndef VIA_BUILD_H
#define VIA_BUILD_H
#define VIA_PKG_NAME    \"${VIA_APP}\"
#define VIA_PKG_VERSION \"${VIA_VERSION}\"
#define VIA_ARTIFACT    \"${VIA_ARTIFACT}\"
#define VIA_PROFILE     \"${VIA_PROFILE}\"
${_features}#endif /* VIA_BUILD_H */
")
endfunction()

# Resolve the artifact's compiled sources. No directory magic: the set comes
# from VIA_SOURCES — absolute file/glob patterns the manifest declares (the
# [[bin]]'s `src`, plus dep/platform `sources`). A "!"-prefixed pattern subtracts
# its matches (gitignore-style); file(GLOB) on an exact path yields that file.
# A [[test]] additionally auto-globs the app's tests/ (the one test assumption).
function(_via_resolve_sources out_srcs)
  set(_inc "")
  set(_exc "")
  foreach(_pat IN LISTS VIA_SOURCES)
    if(_pat MATCHES "^!(.*)$")
      file(GLOB _m CONFIGURE_DEPENDS "${CMAKE_MATCH_1}")
      list(APPEND _exc ${_m})
    else()
      file(GLOB _m CONFIGURE_DEPENDS "${_pat}")
      list(APPEND _inc ${_m})
    endif()
  endforeach()

  if(VIA_KIND STREQUAL "test")
    file(GLOB_RECURSE _tsrcs CONFIGURE_DEPENDS
      "${VIA_APP_DIR}/tests/*.c"  "${VIA_APP_DIR}/tests/*.cpp"
      "${VIA_APP_DIR}/tests/*.cc")
    list(APPEND _inc ${_tsrcs})
  endif()

  if(_exc)
    list(REMOVE_ITEM _inc ${_exc})
  endif()
  set(${out_srcs} ${_inc} PARENT_SCOPE)
endfunction()

# Firmware: apply the (compiler-neutral) bare-metal link policy, linker script,
# .elf suffix and the image/size post-build. Arch flags (-mcpu/-mfpu/...) and the
# chip define are NOT named here — they arrive generically from the manifest's
# cflags/ldflags/defines, which the app declares on its platform.
function(_via_firmware target)
  target_compile_options(${target} PRIVATE -ffunction-sections -fdata-sections)
  target_link_options(${target} PRIVATE
    ${VIA_BAREMETAL_LDFLAGS}
    -Wl,--gc-sections
    "-Wl,-Map=$<TARGET_FILE_DIR:${target}>/${target}.map")

  if(VIA_LINKER_SCRIPT)
    target_link_options(${target} PRIVATE "-T${VIA_LINKER_SCRIPT}")
    set_target_properties(${target} PROPERTIES LINK_DEPENDS "${VIA_LINKER_SCRIPT}")
  endif()

  set_target_properties(${target} PROPERTIES SUFFIX ".elf")

  set(_elf "$<TARGET_FILE:${target}>")
  set(_dir "$<TARGET_FILE_DIR:${target}>")
  add_custom_command(TARGET ${target} POST_BUILD
    COMMAND "${CMAKE_OBJCOPY}" -O binary "${_elf}" "${_dir}/${target}.bin"
    COMMAND "${CMAKE_OBJCOPY}" -O ihex   "${_elf}" "${_dir}/${target}.hex"
    COMMAND "${CMAKE_SIZE}" "${_elf}"
    VERBATIM
    COMMENT "via: ${target}.bin / ${target}.hex + size report")

  install(FILES "${_dir}/${target}.bin" "${_dir}/${target}.hex"
          DESTINATION bin OPTIONAL)
endfunction()

# Dependencies (resolved by the Nix builder):
#   VIA_DEP_LIBS       roots of Via-package (internal lib) deps -> build src/**
#                      + add inc/ (per-consumer, so they honor this toolchain)
#   VIA_EXTRA_INCLUDES include dirs from raw deps (the deps' `includes`)
# (Raw-dep / platform compiled sources are resolved in _via_resolve_sources.)
function(_via_apply_deps target)
  foreach(_libroot IN LISTS VIA_DEP_LIBS)
    file(GLOB_RECURSE _lsrcs CONFIGURE_DEPENDS
      "${_libroot}/src/*.c"  "${_libroot}/src/*.cpp"
      "${_libroot}/src/*.cc" "${_libroot}/src/*.S")
    if(_lsrcs)
      target_sources(${target} PRIVATE ${_lsrcs})
    endif()
    if(EXISTS "${_libroot}/inc")
      target_include_directories(${target} PRIVATE "${_libroot}/inc")
    endif()
  endforeach()
  foreach(_inc IN LISTS VIA_EXTRA_INCLUDES)
    target_include_directories(${target} PRIVATE "${_inc}")
  endforeach()
endfunction()

function(via_build_artifact)
  # --- sources (explicit, from the manifest) ---------------------------------
  _via_resolve_sources(_srcs)
  if(NOT _srcs)
    message(FATAL_ERROR
      "Via: no sources resolved for artifact '${VIA_ARTIFACT}'. A [[bin]] must "
      "declare `src = [ ... ]`; a [[test]] needs files under tests/.")
  endif()

  add_executable(${VIA_ARTIFACT} ${_srcs})

  # --- generated + conventional include dirs ---------------------------------
  set(_gen "${CMAKE_CURRENT_BINARY_DIR}/via")
  _via_generate_build_header("${_gen}")
  target_include_directories(${VIA_ARTIFACT} PRIVATE
    "${_gen}"
    "${VIA_APP_DIR}/inc")

  # --- dependencies (internal libs + raw git deps) ---------------------------
  _via_apply_deps(${VIA_ARTIFACT})

  # --- language standards ----------------------------------------------------
  if(VIA_C_STD)
    set_target_properties(${VIA_ARTIFACT} PROPERTIES
      C_STANDARD ${VIA_C_STD} C_STANDARD_REQUIRED ON)
  endif()
  if(VIA_CXX_STD)
    set_target_properties(${VIA_ARTIFACT} PROPERTIES
      CXX_STANDARD ${VIA_CXX_STD} CXX_STANDARD_REQUIRED ON)
  endif()

  # --- options (defines / cflags / ldflags), already merged by the builder ---
  if(VIA_DEFINES)
    target_compile_definitions(${VIA_ARTIFACT} PRIVATE ${VIA_DEFINES})
  endif()
  if(VIA_CFLAGS)
    target_compile_options(${VIA_ARTIFACT} PRIVATE ${VIA_CFLAGS})
  endif()
  if(VIA_LDFLAGS)
    target_link_options(${VIA_ARTIFACT} PRIVATE ${VIA_LDFLAGS})
  endif()

  # --- firmware: bare-metal link policy + image/size post-build --------------
  if(VIA_PLATFORM_KIND STREQUAL "firmware")
    _via_firmware(${VIA_ARTIFACT})
  endif()

  install(TARGETS ${VIA_ARTIFACT} RUNTIME DESTINATION bin)
endfunction()
